name: Securegate

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  securegate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'

      - name: Install deps
        run: flutter pub get

      - name: Run Securegate
        uses: ./actions
        with:
          fail-threshold: medium
          pr-comment: 'true'
          report-artifact: 'true'
